@startuml
top to bottom direction
scale 1.25

skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam linetype ortho
skinparam shadowing false
skinparam packageStyle rectangle
skinparam packageBorderStyle dashed
skinparam packageBorderColor #444444
skinparam packageBackgroundColor transparent
skinparam package {
	Padding 10
}
skinparam componentStyle rectangle

skinparam ranksep 130
skinparam ArrowFontOffset 50

actor Utilizador

package "Camada de Interface" as L1 {
	component "Ecrãs de interface\nMapa, detalhe, conta, autenticação" as UI
}

package "Camada de Gestão de Estado" as L2 {
	component "Gestão de estado\nflutter_bloc / Cubit" as State
}

package "Camada de Cliente" as L3 {
	component "Serviços e cliente de API" as Client
}

package "Camada de Persistência Local" as L4 {
	component "Armazenamento local\nSessão e consentimento" as Storage
}

package "Backend (NestJS)" as BACKEND {
	component "REST API" as API
}

Utilizador --> UI
UI <--> State : ações / estado
State --> Client : dados
State <--> Storage : sessão
Client --> API : HTTPS (REST)
@enduml
